

<table>
<tr ><th style="background: white; color: grey; font-weight: bold;">Statusas</th><th style="background: white; color: grey; font-weight: bold;">Aprašymas </th></tr>
<tr style="background: white;"><td>Gautas</td><td>Prašymas gautas Paraiškų priėmimo ir dokumentų valdymo skyriuje </td></tr>
<tr style="background: white;" ><td>PZ</td><td>Prašymas vykdomas Prekių ženklų ir dizaino skyriuje </td></tr>
<tr style="background: white;"><td>IS</td><td>Prašymas vykdomas Išradimų skyriuje </td></tr>
<tr style="background: white;"><td>AP</td><td>Prašymas vykdomas Apeliaciniame skyriuje </td></tr>
<tr style="background: white;"><td>PZ&nbsp;OK</td><td>Prašymą įvykdė Prekių ženklų ir dizaino skyrius </td></tr>
<tr style="background: white;"><td>IS&nbsp;OK</td><td>Prašymą įvykdė Išradimų skyrius </td></tr>
<tr style="background: white;"><td>AP&nbsp;OK</td><td>Prašymą įvykdė Apeliacinis skyrius </td></tr>
<tr style="background: white;"><td>PZ&nbsp;atmestas&nbsp;</td><td>Prašymą atmetė Prekių ženklų ir dizaino skyrius </td></tr>
<tr style="background: white;"><td>IS&nbsp;atmestas</td><td>Prašymą atmetė Išradimų skyrius </td></tr>
<tr style="background: white;"><td>AP&nbsp;atmestas</td><td>Prašymą atmetė Apeliacinis skyrius </td></tr>
<tr style='vertical-align:top;  background: white;'><td>OK</td><td>Prašymo įvykdymą patvirtino Paraiškų priėmimo ir dokumentų valdymo skyrius. Prašymas įvykdytas</td></tr>
<tr style='vertical-align:top;  background: white;'><td>Atmestas</td><td>Prašymo atmetimą patvirtino Paraiškų priėmimo ir dokumentų valdymo skyrius. Prašymas atmestas</td></tr>

</table>


